const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const ComplianceDeadline = sequelize.define('ComplianceDeadline', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  
  // Institution Details
  institutionId: {
    type: DataTypes.UUID,
    allowNull: false,
    references: {
      model: 'Institutions',
      key: 'id'
    }
  },
  
  // Deadline Details
  title: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Name/title of the compliance requirement'
  },
  
  description: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Detailed description of the compliance requirement'
  },
  
  // Regulatory Council Information
  councilType: {
    type: DataTypes.ENUM('UGC', 'AICTE', 'NAAC'),
    allowNull: false,
    comment: 'Which council this deadline belongs to'
  },
  
  regulationType: {
    type: DataTypes.ENUM(
      'Annual_Compliance', 
      'Accreditation', 
      'Re_Accreditation', 
      'Quality_Assurance', 
      'Financial_Audit', 
      'Academic_Assessment',
      'Infrastructure_Compliance',
      'Faculty_Compliance',
      'Student_Welfare_Compliance',
      'Research_Compliance',
      'Other'
    ),
    allowNull: false,
    comment: 'Type of regulation this deadline relates to'
  },
  
  // Timeline Management
  dueDate: {
    type: DataTypes.DATE,
    allowNull: false,
    comment: 'Final deadline date'
  },
  
  // Notification Configuration
  notificationEnabled: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    comment: 'Whether notifications are enabled for this deadline'
  },
  
  notificationFrequency: {
    type: DataTypes.ENUM('daily', 'weekly', 'bi_weekly', 'monthly'),
    defaultValue: 'weekly',
    comment: 'How often to send notifications'
  },
  
  advanceNotificationDays: {
    type: DataTypes.ARRAY(DataTypes.INTEGER),
    defaultValue: [90, 60, 30, 14, 7, 3, 1],
    comment: 'Days before due date to send advance notifications'
  },
  
  // Status Management
  status: {
    type: DataTypes.ENUM('pending', 'in_progress', 'completed', 'overdue', 'cancelled'),
    defaultValue: 'pending',
    comment: 'Current status of the compliance requirement'
  },
  
  priority: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'critical'),
    defaultValue: 'medium',
    comment: 'Priority level of this deadline'
  },
  
  // Completion Tracking
  completedDate: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'When the compliance was completed'
  },
  
  completionPercentage: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    validate: {
      min: 0,
      max: 100
    },
    comment: 'Percentage of completion (0-100)'
  },
  
  // Risk Assessment
  riskScore: {
    type: DataTypes.DECIMAL(5, 2),
    defaultValue: 0,
    comment: 'AI-calculated risk score (0-100)'
  },
  
  riskLevel: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'critical'),
    defaultValue: 'low',
    comment: 'Risk level based on AI assessment'
  },
  
  // Document Requirements
  requiredDocuments: {
    type: DataTypes.ARRAY(DataTypes.STRING),
    defaultValue: [],
    comment: 'List of required documents for this compliance'
  },
  
  submittedDocuments: {
    type: DataTypes.ARRAY(DataTypes.STRING),
    defaultValue: [],
    comment: 'List of submitted documents'
  },
  
  documentStatus: {
    type: DataTypes.ENUM('none_submitted', 'partial', 'complete', 'verified'),
    defaultValue: 'none_submitted',
    comment: 'Status of document submission'
  },
  
  // Automated Scheduling
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'Whether this deadline was auto-generated by the system'
  },
  
  parentDeadlineId: {
    type: DataTypes.UUID,
    allowNull: true,
    references: {
      model: 'ComplianceDeadlines',
      key: 'id'
    },
    comment: 'Parent deadline if this is a sub-task'
  },
  
  // Meta Information
  tags: {
    type: DataTypes.ARRAY(DataTypes.STRING),
    defaultValue: [],
    comment: 'Tags for categorization and filtering'
  },
  
  notes: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Additional notes and comments'
  },
  
  // Reminder Settings
  lastNotificationSent: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'When the last notification was sent'
  },
  
  notificationCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    comment: 'Number of notifications sent for this deadline'
  },
  
  // Escalation Settings
  escalationEnabled: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    comment: 'Whether escalation is enabled for overdue deadlines'
  },
  
  escalationDays: {
    type: DataTypes.INTEGER,
    defaultValue: 7,
    comment: 'Days after due date to trigger escalation'
  },
  
  escalated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'Whether this deadline has been escalated'
  },
  
  escalatedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'When escalation was triggered'
  }
}, {
  tableName: 'compliance_deadlines',
  timestamps: true,
  indexes: [
    {
      fields: ['institutionId']
    },
    {
      fields: ['dueDate']
    },
    {
      fields: ['councilType']
    },
    {
      fields: ['status']
    },
    {
      fields: ['priority']
    },
    {
      fields: ['riskScore']
    },
    {
      fields: ['autoGenerated']
    },
    {
      name: 'deadline_due_date_idx',
      fields: ['dueDate', 'status']
    },
    {
      name: 'deadline_risk_idx',
      fields: ['riskScore', 'status']
    },
    {
      name: 'deadline_council_status_idx',
      fields: ['councilType', 'status']
    }
  ]
});

// Instance methods
ComplianceDeadline.prototype.getDaysRemaining = function() {
  const now = new Date();
  const due = new Date(this.dueDate);
  const diffTime = due - now;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
};

ComplianceDeadline.prototype.isOverdue = function() {
  return new Date() > new Date(this.dueDate);
};

ComplianceDeadline.prototype.isCritical = function() {
  const daysRemaining = this.getDaysRemaining();
  return daysRemaining <= 7 || this.riskLevel === 'critical';
};

ComplianceDeadline.prototype.shouldSendNotification = function() {
  if (!this.notificationEnabled) return false;
  
  const daysRemaining = this.getDaysRemaining();
  return this.advanceNotificationDays.includes(daysRemaining);
};

// Class methods
ComplianceDeadline.getUpcomingDeadlines = function(institutionId, days = 30) {
  const startDate = new Date();
  const endDate = new Date();
  endDate.setDate(endDate.getDate() + days);
  
  return this.findAll({
    where: {
      institutionId,
      dueDate: {
        [sequelize.Sequelize.Op.between]: [startDate, endDate]
      },
      status: ['pending', 'in_progress']
    },
    order: [['dueDate', 'ASC']]
  });
};

ComplianceDeadline.getOverdueDeadlines = function(institutionId) {
  return this.findAll({
    where: {
      institutionId,
      dueDate: {
        [sequelize.Sequelize.Op.lt]: new Date()
      },
      status: ['pending', 'in_progress']
    },
    order: [['dueDate', 'ASC']]
  });
};

ComplianceDeadline.getHighRiskDeadlines = function(institutionId, minRiskScore = 70) {
  return this.findAll({
    where: {
      institutionId,
      riskScore: {
        [sequelize.Sequelize.Op.gte]: minRiskScore
      },
      status: ['pending', 'in_progress']
    },
    order: [['riskScore', 'DESC']]
  });
};

module.exports = ComplianceDeadline;