// Phase 1 Types for Critical Penalty Avoidance Features

export interface ComplianceDeadline {
  id: string;
  institutionId: string;
  title: string;
  description?: string;
  councilType: 'UGC' | 'AICTE' | 'NAAC';
  regulationType: 'Annual_Compliance' | 'Accreditation' | 'Re_Accreditation' | 'Quality_Assurance' | 'Financial_Audit' | 'Academic_Assessment' | 'Infrastructure_Compliance' | 'Faculty_Compliance' | 'Student_Welfare_Compliance' | 'Research_Compliance' | 'Other';
  dueDate: string;
  notificationEnabled: boolean;
  notificationFrequency: 'daily' | 'weekly' | 'bi_weekly' | 'monthly';
  advanceNotificationDays: number[];
  status: 'pending' | 'in_progress' | 'completed' | 'overdue' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'critical';
  completedDate?: string;
  completionPercentage: number;
  riskScore: number;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  requiredDocuments: string[];
  submittedDocuments: string[];
  documentStatus: 'none_submitted' | 'partial' | 'complete' | 'verified';
  autoGenerated: boolean;
  parentDeadlineId?: string;
  tags: string[];
  notes?: string;
  lastNotificationSent?: string;
  notificationCount: number;
  escalationEnabled: boolean;
  escalationDays: number;
  escalated: boolean;
  escalatedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RiskAssessment {
  id: string;
  deadlineId: string;
  institutionId: string;
  violationProbability: number;
  riskScore: number;
  riskLevel: 'very_low' | 'low' | 'medium' | 'high' | 'critical' | 'extreme';
  assessmentType: 'automated' | 'manual' | 'scheduled' | 'triggered';
  assessmentDate: string;
  timePressureScore: number;
  complexityScore: number;
  resourceAdequacyScore: number;
  historicalComplianceScore: number;
  documentReadinessScore: number;
  aiModelVersion?: string;
  confidenceLevel: number;
  riskTriggers: Record<string, any>;
  riskWarnings: string[];
  recommendations: Array<{
    id: string;
    title: string;
    description: string;
    priority: 'low' | 'medium' | 'high' | 'critical';
    estimatedImpact: string;
    implementationEffort: string;
  }>;
  priorityActions: Array<{
    id: string;
    action: string;
    deadline?: string;
    assignedTo?: string;
    status: 'pending' | 'in_progress' | 'completed';
  }>;
  predictedCompletionDate?: string;
  completionProbability: number;
  assessmentFactors: Record<string, any>;
  factorWeights: Record<string, number>;
  bestCaseScenario: Record<string, any>;
  worstCaseScenario: Record<string, any>;
  likelyCaseScenario: Record<string, any>;
  riskPercentile: number;
  industryBenchmark: Record<string, any>;
  actionItems: Array<{
    id: string;
    title: string;
    description: string;
    deadline?: string;
    priority: 'low' | 'medium' | 'high' | 'critical';
    status: 'pending' | 'in_progress' | 'completed';
    assignedTo?: string;
  }>;
  escalationRecommended: boolean;
  nextAssessmentDate?: string;
  assessmentFrequency: 'daily' | 'weekly' | 'bi_weekly' | 'monthly' | 'quarterly';
  modelAccuracy: number;
  dataQualityScore: number;
  assessmentNotes?: string;
  isActive: boolean;
  supersededBy?: string;
  validationPassed: boolean;
  validationErrors: string[];
  createdAt: string;
  updatedAt: string;
}

export interface AlertNotification {
  id: string;
  deadlineId?: string;
  riskAssessmentId?: string;
  institutionId: string;
  recipientType: 'individual' | 'role' | 'department' | 'all_stakeholders';
  recipientId?: string;
  recipientName: string;
  recipientEmail?: string;
  recipientPhone?: string;
  recipientWhatsApp?: string;
  notificationType: 'deadline_reminder' | 'risk_alert' | 'overdue_warning' | 'escalation' | 'completion_confirmation' | 'status_update';
  priority: 'low' | 'medium' | 'high' | 'urgent' | 'critical';
  urgency: 'normal' | 'high' | 'emergency';
  channels: ('email' | 'sms' | 'whatsapp' | 'phone' | 'push' | 'in_app')[];
  subject?: string;
  message: string;
  shortMessage?: string;
  status: 'pending' | 'scheduled' | 'sent' | 'delivered' | 'failed' | 'read' | 'acknowledged' | 'cancelled';
  scheduledFor?: string;
  sentAt?: string;
  deliveredAt?: string;
  readAt?: string;
  acknowledgedAt?: string;
  emailStatus?: 'pending' | 'sent' | 'delivered' | 'failed' | 'bounced' | 'opened' | 'clicked';
  smsStatus?: 'pending' | 'sent' | 'delivered' | 'failed' | 'undelivered';
  whatsappStatus?: 'pending' | 'sent' | 'delivered' | 'failed' | 'read';
  phoneStatus?: 'pending' | 'calling' | 'answered' | 'voicemail' | 'failed' | 'busy' | 'no_answer';
  pushStatus?: 'pending' | 'sent' | 'delivered' | 'failed' | 'clicked';
  emailMessageId?: string;
  smsMessageId?: string;
  whatsappMessageId?: string;
  retryCount: number;
  maxRetries: number;
  retryDelay: number;
  nextRetryAt?: string;
  errorMessage?: string;
  errorCode?: string;
  failureReason?: 'invalid_recipient' | 'service_unavailable' | 'rate_limit_exceeded' | 'content_filtered' | 'network_error' | 'unknown';
  templateId?: string;
  templateVariables?: Record<string, any>;
  escalationLevel: number;
  escalationPath: Array<{
    level: number;
    recipientType: string;
    recipientId?: string;
    recipientName: string;
    triggeredAt?: string;
  }>;
  escalated: boolean;
  escalatedAt?: string;
  clickCount: number;
  engagementScore: number;
  consentStatus: 'granted' | 'denied' | 'pending' | 'withdrawn';
  communicationLog?: string;
  requiresResponse: boolean;
  responseReceived: boolean;
  responseContent?: string;
  responseAt?: string;
  campaignId?: string;
  batchId?: string;
  tags: string[];
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// API Response Types
export interface RiskAssessmentResponse {
  success: boolean;
  data: RiskAssessment;
  message?: string;
}

export interface ComplianceDeadlinesResponse {
  success: boolean;
  data: ComplianceDeadline[];
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
  message?: string;
}

export interface AlertNotificationsResponse {
  success: boolean;
  data: AlertNotification[];
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
  message?: string;
}

// Dashboard Widget Types
export interface RiskDashboardWidget {
  id: string;
  title: string;
  type: 'risk_score' | 'upcoming_deadlines' | 'high_risk_items' | 'recent_assessments' | 'notification_summary';
  data: any;
  priority: 'low' | 'medium' | 'high' | 'critical';
  lastUpdated: string;
}

export interface NotificationSummary {
  total: number;
  pending: number;
  sent: number;
  delivered: number;
  failed: number;
  byPriority: Record<string, number>;
  byChannel: Record<string, number>;
}

export interface DeadlineSummary {
  total: number;
  pending: number;
  inProgress: number;
  completed: number;
  overdue: number;
  byCouncil: Record<string, number>;
  byPriority: Record<string, number>;
}

export interface RiskSummary {
  averageRiskScore: number;
  highRiskCount: number;
  criticalRiskCount: number;
  assessmentsUpdated: number;
  riskDistribution: Record<string, number>;
  topRiskFactors: Array<{
    factor: string;
    impact: number;
    frequency: number;
  }>;
}

// Filter and Query Types
export interface DeadlineFilters {
  councilType?: string[];
  regulationType?: string[];
  status?: string[];
  priority?: string[];
  riskLevel?: string[];
  dueDateFrom?: string;
  dueDateTo?: string;
  tags?: string[];
  search?: string;
}

export interface RiskAssessmentFilters {
  riskLevel?: string[];
  assessmentType?: string[];
  isActive?: boolean;
  assessmentDateFrom?: string;
  assessmentDateTo?: string;
  minRiskScore?: number;
  maxRiskScore?: number;
  escalationRecommended?: boolean;
  search?: string;
}

export interface NotificationFilters {
  notificationType?: string[];
  status?: string[];
  priority?: string[];
  channels?: string[];
  recipientType?: string[];
  scheduledFrom?: string;
  scheduledTo?: string;
  search?: string;
}

// Form Types
export interface CreateDeadlineForm {
  title: string;
  description?: string;
  councilType: 'UGC' | 'AICTE' | 'NAAC';
  regulationType: string;
  dueDate: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  requiredDocuments?: string[];
  notes?: string;
  tags?: string[];
}

export interface UpdateDeadlineForm extends Partial<CreateDeadlineForm> {
  status?: 'pending' | 'in_progress' | 'completed' | 'overdue' | 'cancelled';
  completionPercentage?: number;
  submittedDocuments?: string[];
}

export interface CreateRiskAssessmentForm {
  deadlineId: string;
  assessmentType: 'automated' | 'manual' | 'scheduled' | 'triggered';
  assessmentNotes?: string;
}

export interface SendNotificationForm {
  deadlineId?: string;
  riskAssessmentId?: string;
  recipientType: 'individual' | 'role' | 'department' | 'all_stakeholders';
  recipientIds?: string[];
  notificationType: string;
  priority: 'low' | 'medium' | 'high' | 'urgent' | 'critical';
  urgency: 'normal' | 'high' | 'emergency';
  channels: string[];
  subject?: string;
  message: string;
  scheduledFor?: string;
  templateId?: string;
  templateVariables?: Record<string, any>;
  requiresResponse?: boolean;
  tags?: string[];
}